/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/screens/{screen}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScreen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAttempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAssignments"];
        put?: never;
        post: operations["createAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGroups"];
        put?: never;
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStudents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInvites"];
        put?: never;
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLessons"];
        put?: never;
        post: operations["createLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lessonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLesson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateLesson"];
        trace?: never;
    };
    "/read-models/{model}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail: string;
            instance: string;
            requestId: string;
            errors?: Record<string, never>[];
        };
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            role: "student" | "tutor";
            grade?: number;
            school?: string;
            subjects?: string[];
            yearsExp?: number;
            rate?: number;
            meetingUrl?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        CurrentUser: {
            user: {
                [key: string]: unknown;
            };
            profile?: {
                [key: string]: unknown;
            } | null;
            home: string;
        };
        /** @enum {string} */
        ScreenName: "login" | "index" | "tutor" | "students" | "groups" | "group" | "invites" | "invite" | "lesson" | "homework" | "task" | "tutor-check" | "stats" | "bank" | "account" | "parent";
        ScreenState: {
            [key: string]: unknown;
        };
        CreateInviteRequest: {
            /** @enum {string} */
            kind: "enrollment" | "group";
            subjectId?: string;
            groupId?: string;
            maxUses?: number | null;
            /** Format: date-time */
            expiresAt?: string | null;
            note?: string;
        };
        CreateGroupRequest: {
            subjectId: string;
            title: string;
            level?: string;
            schedule?: string;
            capacity?: number;
        };
        CreateLessonRequest: {
            enrollmentId?: string | null;
            groupId?: string | null;
            /** Format: date-time */
            startsAt: string;
            durationMin?: number;
        };
        CreateAssignmentRequest: {
            enrollmentId?: string;
            groupId?: string;
            lessonId?: string | null;
            title: string;
            /** Format: date-time */
            dueAt?: string;
            taskIds: string[];
        };
        PageInfo: {
            limit: number;
            hasMore: boolean;
            nextCursor: string | null;
        };
        Paginated: {
            items: unknown[];
            page: components["schemas"]["PageInfo"];
            meta: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Ошибка в формате RFC 9457 Problem Details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Команда выполнена */
        CommandSuccess: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Специализированный bootstrap экрана без эталонных ответов */
        ScreenState: {
            headers: {
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ScreenState"];
            };
        };
        /** @description Страница ресурсов */
        Paginated: {
            headers: {
                ETag?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Paginated"];
            };
        };
    };
    parameters: {
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Доступные роли */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            200: components["responses"]["CommandSuccess"];
            422: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["CommandSuccess"];
            401: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CommandSuccess"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущий пользователь и профиль */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ScreenState"];
        };
    };
    getScreen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                screen: components["schemas"]["ScreenName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ScreenState"];
            404: components["responses"]["Problem"];
        };
    };
    listTasks: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                sort?: "id" | "name" | "title" | "number" | "createdAt" | "startsAt" | "dueAt" | "submittedAt";
                order?: "asc" | "desc";
                subject?: string;
                status?: string;
                student?: string;
                tutor?: string;
                group?: string;
                lesson?: string;
                assignment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Paginated"];
        };
    };
    listAttempts: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                sort?: "id" | "name" | "title" | "number" | "createdAt" | "startsAt" | "dueAt" | "submittedAt";
                order?: "asc" | "desc";
                subject?: string;
                status?: string;
                student?: string;
                tutor?: string;
                group?: string;
                lesson?: string;
                assignment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Paginated"];
        };
    };
    listReviews: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                sort?: "id" | "name" | "title" | "number" | "createdAt" | "startsAt" | "dueAt" | "submittedAt";
                order?: "asc" | "desc";
                subject?: string;
                status?: string;
                student?: string;
                tutor?: string;
                group?: string;
                lesson?: string;
                assignment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Paginated"];
        };
    };
    listAssignments: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                sort?: "id" | "name" | "title" | "number" | "createdAt" | "startsAt" | "dueAt" | "submittedAt";
                order?: "asc" | "desc";
                subject?: string;
                status?: string;
                student?: string;
                tutor?: string;
                group?: string;
                lesson?: string;
                assignment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Paginated"];
        };
    };
    createAssignment: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAssignmentRequest"];
            };
        };
        responses: {
            200: components["responses"]["CommandSuccess"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listGroups: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                sort?: "id" | "name" | "title" | "number" | "createdAt" | "startsAt" | "dueAt" | "submittedAt";
                order?: "asc" | "desc";
                subject?: string;
                status?: string;
                student?: string;
                tutor?: string;
                group?: string;
                lesson?: string;
                assignment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Paginated"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            200: components["responses"]["CommandSuccess"];
            422: components["responses"]["Problem"];
        };
    };
    listStudents: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                sort?: "id" | "name" | "title" | "number" | "createdAt" | "startsAt" | "dueAt" | "submittedAt";
                order?: "asc" | "desc";
                subject?: string;
                status?: string;
                student?: string;
                tutor?: string;
                group?: string;
                lesson?: string;
                assignment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Paginated"];
        };
    };
    listInvites: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                sort?: "id" | "name" | "title" | "number" | "createdAt" | "startsAt" | "dueAt" | "submittedAt";
                order?: "asc" | "desc";
                subject?: string;
                status?: string;
                student?: string;
                tutor?: string;
                group?: string;
                lesson?: string;
                assignment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Paginated"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteRequest"];
            };
        };
        responses: {
            200: components["responses"]["CommandSuccess"];
            409: components["responses"]["Problem"];
        };
    };
    acceptInvite: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            200: components["responses"]["CommandSuccess"];
            409: components["responses"]["Problem"];
        };
    };
    listLessons: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                sort?: "id" | "name" | "title" | "number" | "createdAt" | "startsAt" | "dueAt" | "submittedAt";
                order?: "asc" | "desc";
                subject?: string;
                status?: string;
                student?: string;
                tutor?: string;
                group?: string;
                lesson?: string;
                assignment?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Paginated"];
        };
    };
    createLesson: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLessonRequest"];
            };
        };
        responses: {
            200: components["responses"]["CommandSuccess"];
            422: components["responses"]["Problem"];
        };
    };
    getLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Занятие */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateLesson: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path: {
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "planned" | "done" | "moved" | "cancelled" | "missed";
                };
            };
        };
        responses: {
            200: components["responses"]["CommandSuccess"];
            412: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
        };
    };
    getReadModel: {
        parameters: {
            query?: {
                student?: string;
            };
            header?: never;
            path: {
                model: "student-dashboard" | "tutor-today" | "assignment-progress" | "student-subject-stats";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Проекция, построенная из первичных фактов */
            200: {
                headers: {
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            [key: string]: unknown;
                        }[];
                        /** Format: date-time */
                        updatedAt: string;
                    };
                };
            };
            404: components["responses"]["Problem"];
        };
    };
}
