const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const test=require('node:test');const assert=require('node:assert/strict');const request=require('supertest');const {registerAndLogin}=require('../helpers/auth.js');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'token-stage5-'));process.env.NODE_ENV='test';process.env.LOG_LEVEL='silent';process.env.TOKEN_DB=path.join(dir,'db.sqlite');process.env.COOKIE_SECURE='false';
const {createApp}=require('../../server/app.js');const {loadConfig}=require('../../server/config.js');const {db}=require('../../server/db.js');const app=createApp({config:loadConfig()});
test.after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true});});
test('stage 5 completes profile, relationship, schedule, homework and assessment lifecycles',async()=>{
 const tutor=request.agent(app),student=request.agent(app);await registerAndLogin(tutor,{name:'Stage Tutor',email:'stage-t@example.test',password:'test-password',role:'tutor',subjects:['inf']});await registerAndLogin(student,{name:'Stage Student',email:'stage-s@example.test',password:'test-password',role:'student',grade:10});
 assert.equal((await student.put('/api/profile').send({name:'Updated Student',phone:'+79990000000',tz:'Europe/Moscow',grade:11,school:'Лицей'})).status,200);
 const inv=await tutor.post('/api/invites').send({kind:'enrollment',subjectId:'inf'});await student.post('/api/invites/accept').send({code:inv.body.invite.code});let state=(await tutor.get('/api/state')).body;const enr=state.enrollments[0];
 const dry=await tutor.post('/api/students/import').send({dryRun:true,students:[{name:'Новый Ученик',email:'new@example.test',subjectId:'inf',grade:9}]});assert.equal(dry.status,200);assert.equal(dry.body.dryRun,true);const imported=await tutor.post('/api/students/import').send({dryRun:false,students:dry.body.students});assert.equal(imported.status,200,JSON.stringify(imported.body));assert.equal(imported.body.invites.length,1);
 assert.equal((await tutor.put(`/api/enrollments/${enr.id}`).send({status:'paused',reason:'каникулы'})).status,200);assert.equal(db.prepare('select count(*) n from enrollment_history').get().n,1);await tutor.put(`/api/enrollments/${enr.id}`).send({status:'active',reason:'возобновлено'});
 const startsAt=new Date(Date.now()+86400000).toISOString();const series=await tutor.post('/api/lessons').send({enrollmentId:enr.id,startsAt,durationMin:60,recurrence:{intervalWeeks:1,count:3}});assert.equal(series.status,200,JSON.stringify(series.body));assert.equal(series.body.ids.length,3);
 const conflict=await tutor.post('/api/lessons').send({enrollmentId:enr.id,startsAt,durationMin:60});assert.equal(conflict.status,409);
 assert.equal((await tutor.put(`/api/lessons/${series.body.id}/attendance/${enr.studentId}`).send({status:'present'})).status,200);
 const task=(await tutor.get('/api/tasks?subject=inf')).body[0];const asg=await tutor.post('/api/assignments').send({enrollmentId:enr.id,title:'Черновик жизненного цикла',dueAt:new Date(Date.now()+172800000).toISOString(),taskIds:[task.id]});assert.equal(asg.status,200);
 assert.equal((await tutor.put(`/api/assignments/${asg.body.id}`).send({status:'closed',latePolicy:'block'})).status,200);
 assert.equal((await student.put(`/api/goals/${enr.studentId}/inf`).send({targetScore:85,examDate:'2027-06-01'})).status,200);
 const mock=await student.post('/api/mock-exams').send({subjectId:'inf',variant:'1',date:new Date().toISOString(),items:[{number:1,score:1}],scaleVersion:'ege-2026'});assert.equal(mock.status,200);assert.equal((await student.put(`/api/mock-exams/${mock.body.id}`).send({variant:'2',date:new Date().toISOString(),items:[],scaleVersion:'ege-2026'})).status,200);assert.equal((await student.delete(`/api/mock-exams/${mock.body.id}`)).status,200);
});
